apiVersion: v1
entries:
  myapp:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-02-27T10:22:32.442179+03:00"
    description: A Helm chart for Kubernetes
    digest: 02caf4980fa0aa8dc4bf08c7508eca4543d5ca5831cba33af041798fdd1bc794
    name: myapp
    type: application
    urls:
    - https://github.com/muhammedsaidkaya/chart-museum-test/myapp-0.1.0.tgz
    version: 0.1.0
generated: "2022-02-27T10:22:32.441262+03:00"
